/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package locationcore */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 11 "bridge.go"


#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* locationcore_version();

/* Return type for locationcore_generateca */
struct locationcore_generateca_return {
	char* r0; /* certOut */
	char* r1; /* keyOut */
};
extern struct locationcore_generateca_return locationcore_generateca();
extern int locationcore_validateca(char* certData, char* keyData);
extern uintptr_t locationcore_startproxy(char* certData, char* keyData, double lat, double lon, int enabled, int accuracy);
extern uintptr_t locationcore_startproxyv2(char* certData, char* keyData, double lat, double lon, int enabled, int accuracy, int motionRadius);
extern int locationcore_stopproxy(uintptr_t handle);
extern void locationcore_setpatchconfig(double lat, double lon, int enabled, int accuracy, int motionRadius);
extern void locationcore_setcoords(double lat, double lon, int enabled, int accuracy);

/* Return type for locationcore_getcoords */
struct locationcore_getcoords_return {
	double r0; /* lat */
	double r1; /* lon */
	int r2; /* enabled */
};
extern struct locationcore_getcoords_return locationcore_getcoords();
extern char* locationcore_drainlogs();
extern uintptr_t locationcore_startcertservice(char* certData, char* keyData);
extern int locationcore_certservice_httpport(uintptr_t handle);
extern int locationcore_certservice_httpsport(uintptr_t handle);
extern char* locationcore_certservice_leafsha256(uintptr_t handle);
extern int locationcore_stopcertservice(uintptr_t handle);
extern char* locationcore_testpatch(double lat, double lon, int accuracy);
extern char* locationcore_samplerequesthex();
extern char* locationcore_refreshverifytoken();
extern int locationcore_checkverifytoken(char* token);

#ifdef __cplusplus
}
#endif
